### ISSUE TITLE
no indication of selection in comments

### ISSUE THREAD

**Issue by braver** [carlo/summerfruit-theme#1]
Comments have a greenish background. If you select text, it doesn't change so you can't see what you've selected.

![screen shot 2015-01-06 at 19 10 46](https://cloud.githubusercontent.com/assets/2543659/5633445/beb76d6e-95d7-11e4-9e3a-919a4e572009.png)

**Comment by czottmann** [comment]
Fixed in 1.4.0, thanks for the heads-up!

**Comment by braver** [comment]
:trophy:
