### ISSUE TITLE
Deprecated selector in `summerfruit-theme/index.less`

### ISSUE THREAD

**Issue by suzumiyasmith** [carlo/summerfruit-theme#2]
In `summerfruit-theme/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `:host,
atom-text-editor` => `atom-text-editor,
atom-text-editor`

* `:host .gutter:last-child,
atom-text-editor .gutter:last-child` => `atom-text-editor .gutter:last-child,
atom-text-editor .gutter:last-child`

* `:host .gutter .line-number.cursor-line,
atom-text-editor .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,
atom-text-editor .gutter .line-number.cursor-line`

* `:host .gutter .line-number.cursor-line-no-selection,
atom-text-editor .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,
atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `:host .wrap-guide,
atom-text-editor .wrap-guide` => `atom-text-editor .wrap-guide,
atom-text-editor .wrap-guide`

* `:host .indent-guide,
atom-text-editor .indent-guide` => `atom-text-editor .indent-guide,
atom-text-editor .indent-guide`

* `:host .invisible-character,
atom-text-editor .invisible-character` => `atom-text-editor .invisible-character,
atom-text-editor .invisible-character`

* `:host .search-results .marker .region,
atom-text-editor .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,
atom-text-editor .search-results .syntax--marker .region`

* `:host .search-results .marker.current-result .region,
atom-text-editor .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,
atom-text-editor .search-results .syntax--marker.current-result .region`

* `:host .cursor,
atom-text-editor.is-focused .cursor` => `atom-text-editor .cursor,
atom-text-editor.is-focused .cursor`

* `:host .selection .region,
atom-text-editor.is-focused .selection .region` => `atom-text-editor .selection .region,
atom-text-editor.is-focused .selection .region`

* `:host .line-number.cursor-line-no-selection,
:host .line.cursor-line,
atom-text-editor.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line.cursor-line` => `atom-text-editor .line-number.cursor-line-no-selection,atom-text-editor .line.cursor-line,
atom-text-editor.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line.cursor-line`

* `.comment` => `.syntax--comment`

* `.constant` => `.syntax--constant`

* `.entity` => `.syntax--entity`

* `.keyword` => `.syntax--keyword`

* `.storage` => `.syntax--storage`

* `.string` => `.syntax--string`

* `.support` => `.syntax--support`

* `.variable` => `.syntax--variable`

* `.invalid` => `.syntax--invalid`

* `.entity.name.tag` => `.syntax--entity.syntax--name.syntax--tag`

* `.entity.other.attribute-name` => `.syntax--entity.syntax--other.syntax--attribute-name`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by suzumiyasmith** [comment]
Thanks for your devotion of this package. I really love summer fruit.

**Comment by czottmann** [comment]
It's on my radar as well as my todo list, I just haven't found the time to fix it.

Glad you like it! :)

**Comment by czottmann** [comment]
Fixed in 1.8.0, which was just released.
